/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.members-local.jsonc --include-runtime=false --strict-vars=false --env-interface=MemberBindings member-worker-configuration.d.ts` (hash: 31fbb86b213c439d38ef8cbe1dedc1f7)
interface __BaseEnv_MemberBindings {
	AUTH_DB: D1Database;
	DB: D1Database;
	MEMBER_AUTH_ENABLED: string;
	MEMBER_AUTH_LOCAL_DEV: string;
	BETTER_AUTH_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/member-prototype");
	}
	interface Env extends __BaseEnv_MemberBindings {}
}
interface MemberBindings extends __BaseEnv_MemberBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MEMBER_AUTH_ENABLED" | "MEMBER_AUTH_LOCAL_DEV" | "BETTER_AUTH_SECRET" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET">> {}
}
